--EX01
SELECT CODIGO, DESCRICAO, VALOR::MONEY,
CUSTO::MONEY, (VALOR-CUSTO)::MONEY AS LUCRO FROM PRODUTO;
--EX02
SELECT CODIGO, DESCRICAO, VALOR::MONEY,
CUSTO::MONEY, (VALOR-CUSTO)::MONEY AS LUCRO FROM PRODUTO WHERE (VALOR - CUSTO) < 0;
--EX03
UPDATE PRODUTO SET VALOR = (VALOR+(VALOR*0.6)) WHERE CODIGO = 'P11' OR CODIGO = 'P12';
--EX04
UPDATE PRODUTO SET CUSTO = (CUSTO/2) WHERE CODIGO = 'P11';
--EX05
SELECT CODIGO, DESCRICAO, TO_CHAR(DATACADASTRO,'DD/MM/YYYY'), VALOR::MONEY, CUSTO::MONEY,
(VALOR-CUSTO)::MONEY AS LUCRO FROM PRODUTO;
--EX06
SELECT CODIGO, DESCRICAO, TO_CHAR(DATACADASTRO,'DD/MM/YYYY'), VALOR::MONEY, CUSTO::MONEY,
(VALOR-CUSTO)::MONEY AS LUCRO FROM PRODUTO WHERE (VALOR - CUSTO) <= 1.00;
--EX07
ALTER TABLE PRODUTO ADD COLUMN IMPOSTO NUMERIC(10,2);
UPDATE PRODUTO SET IMPOSTO = (CUSTO*0.15) WHERE TIPO = 'Bebidas';
UPDATE PRODUTO SET IMPOSTO = (CUSTO*0.12) WHERE TIPO = 'Farenaceos';
UPDATE PRODUTO SET IMPOSTO = (CUSTO*0.14) WHERE TIPO = 'Doces';
UPDATE PRODUTO SET IMPOSTO = 0 WHERE TIPO = 'Feira';
--EX08
SELECT CODIGO, DESCRICAO, UNIDADEMEDIDA, VALOR::MONEY, CUSTO::MONEY,
(CUSTO+IMPOSTO)::MONEY AS CUSTO_REAL, (VALOR-(CUSTO+IMPOSTO))::MONEY AS LUCRO_REAL FROM PRODUTO;
--EX09
SELECT DESCRICAO, TO_CHAR(DATACADASTRO,'DD/MM/YYYY') FROM PRODUTO WHERE DATACADASTRO
BETWEEN '01/02/2022' AND '01/03/2022' AND QTDESTOQUE > 100;
--EX10
ALTER TABLE PRODUTO ADD COLUMN CUSTO_REAL NUMERIC(10,2);
UPDATE PRODUTO SET CUSTO_REAL = (CUSTO+IMPOSTO);
ALTER TABLE PRODUTO ADD COLUMN LUCRO_REAL NUMERIC(10,2);
UPDATE PRODUTO SET LUCRO_REAL = (VALOR-(CUSTO+IMPOSTO));
SELECT CODIGO, TO_CHAR(DATACADASTRO,'DD/MM/YYYY'), UNIDADEMEDIDA,
DESCRICAO, VALOR::MONEY, CUSTO::MONEY, LUCRO_REAL::MONEY, CUSTO_REAL::MONEY FROM PRODUTO;