--Começo do exercício 
--EX02
SELECT CODIGO, DESCRICAO, UNIDADEMEDIDA, TO_CHAR (DATACADASTRO, 'DD,MM,YYYY') FROM PRODUTO
WHERE TIPO = 'Farinaceos';
--EX03
SELECT CODIGO, DESCRICAO, VALOR, TO_CHAR (CUSTO, 'L999G999G990D99') FROM PRODUTO
WHERE QTDESTOQUE > 400;
--EX04
SELECT ID, CODIGO, DESCRICAO, UNIDADEMEDIDA, VALOR, CUSTO, INATIVO, TO_CHAR(DATACADASTRO, 'DD/MM/YYYY')  FROM PRODUTO
WHERE DATACADASTRO BETWEEN '01/01/2024' AND '01/01/2025';
--EX05
SELECT CODIGO, UPPER(DESCRICAO) FROM PRODUTO;
--EX06
SELECT * FROM PRODUTO
WHERE UNIDADEMEDIDA = 'UN';
--EX07
SELECT * FROM PRODUTO
WHERE UNIDADEMEDIDA = 'KG';
--EX08
SELECT * FROM PRODUTO
WHERE DESCRICAO LIKE '%G' AND DESCRICAO NOT LIKE '%KG';
--EX09
SELECT DESCRICAO, VALOR, TO_CHAR (CUSTO, 'L999G999G990D99') FROM PRODUTO
WHERE CUSTO < VALOR;
--EX10
SELECT DESCRICAO, VALOR, TO_CHAR (CUSTO, 'L999G999G990D99') FROM PRODUTO
WHERE CUSTO > VALOR;